name: Example push image to snowflake

# on:
#   push:
#     branches:
#       - main

# manual by default
on:
  workflow_dispatch:


jobs:
  build_and_push_image:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Snowflake Login
        env:
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
          SNOWFLAKE_REGISTRY_NAME: ${{ secrets.SNOWFLAKE_REGISTRY_NAME }}

        run: |
          docker login $SNOWFLAKE_ACCOUNT.registry.snowflakecomputing.com -u $SNOWFLAKE_USER -p $SNOWFLAKE_PASSWORD

      - name: Build Image
        run: |
          docker build -t $SNOWFLAKE_ACCOUNT.registry.snowflakecomputing.com/$SNOWFLAKE_DATABASE/$SNOWFLAKE_SCHEMA/$SNOWFLAKE_REGISTRY_NAME/<YOUR IMAGE NAME>:latest .

      - name: Push Image
        run: |
          docker push $SNOWFLAKE_ACCOUNT.registry.snowflakecomputing.com/$SNOWFLAKE_DATABASE/$SNOWFLAKE_SCHEMA/$SNOWFLAKE_REGISTRY_NAME/<YOUR IMAGE NAME>:latest